# Generated by Django 2.0.5 on 2019-02-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20190223_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
    ]
